# Generated by Django 5.2.3 on 2025-06-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Sku', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Unit', models.CharField(max_length=20)),
                ('Current_Stock', models.PositiveIntegerField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_project.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Type', models.CharField(max_length=5)),
                ('Quantity', models.PositiveIntegerField()),
                ('Reference_Note', models.CharField(max_length=20)),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_project.item')),
            ],
        ),
    ]
