# Generated by Django 5.2.3 on 2025-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
