# Generated by Django 5.2.3 on 2025-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0002_alter_category_description_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Current_Stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
