# Generated by Django 5.2.3 on 2025-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0003_alter_item_current_stock_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(max_length=100)),
                ('Notes', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock_Transaction',
        ),
    ]
