# Generated by Django 5.2.3 on 2025-06-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0005_stock_transactions_delete_addreduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_transactions',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_project.item'),
        ),
        migrations.AlterField(
            model_name='stock_transactions',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
