# Generated by Django 5.2.3 on 2025-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0006_alter_stock_transactions_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_transactions',
            name='Reference_note',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_transactions',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
