# Generated by Django 5.2.3 on 2025-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0007_stock_transactions_reference_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
