# Generated by Django 5.2.3 on 2025-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0008_addcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
