# Generated by Django 5.0.6 on 2025-07-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0010_category_user_item_user_stock_transactions_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Current_Stock',
            new_name='current_stock',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Sku',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Reference_note',
            new_name='reference_note',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='stock_transactions',
            old_name='User',
            new_name='user',
        ),
    ]
