# Generated by Django 5.0.6 on 2025-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0011_rename_created_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_transactions',
            name='type',
            field=models.CharField(choices=[('IN', 'Add'), ('OUT', 'Reduce')], max_length=3),
        ),
    ]
